### ISSUE TITLE
Which features should we add to the visualisation?

### ISSUE THREAD

**Issue by sarah37** [sarah37/ds4d-project#2]
I put together the pies and heatmaps into one page, the question now is what else we should add? 

Things that I think are essential: 
- expanding the themes in the heatmaps to show all the questions inside the theme
- styling
- adding some explanation on how to read it, and maybe also on the background of the data

Optional in my opinion:
 - a checkbox or switch to scale the pies by population or not (could be helpful for the pies where some groups are really small)

Question would now be - how do we prioritise this? What can we still get done? How should we distribute the work? Do you have any other ideas for what to add?

[Link to the current version](http://sarah37.github.io/ds4d-project/Sketches/pie_and_heatmap/)

**Comment by Huiling0220** [comment]
I think adding some explanation to read is important, and for expanding the themes, Yan should have been doing that now?

**Comment by ianz88** [comment]
I have added some heatmaps by questions. I'll try to make some template styling to make it more presentable

**Comment by Huiling0220** [comment]
I have a new question, is that possible that we organise each pie chart according to order of the length size? because in some chart, the length is very close, and if they are not close to each other, it's difficult to compare

**Comment by ianz88** [comment]
That's good idea Huiling, it should help with the visibility

**Comment by sarah37** [comment]
All of the things listed in my original post are done now, and Huiling's suggestion (to sort pie charts by length) is also implemented. Therefore closing this issue!
