### ISSUE TITLE
Example picture for explaining the pie chart

### ISSUE THREAD

**Issue by Huiling0220** [sarah37/ds4d-project#3]
I've uploaded the example graph that explains how to read the pie chart, could you please have a look and give me improvement ideas? @sarah37 @ianz88 
![examples for explaining the pie chart](https://user-images.githubusercontent.com/44260637/49091897-a8553380-f258-11e8-9aff-800edbf42bf0.png)

**Comment by Huiling0220** [comment]
Do we need to explain how to read color here? I think from the angle and length we have included everything, I'm not sure whether to explain color here or not

**Comment by sarah37** [comment]
I think it's good like this, just need to update it with the style changes I'm in the process of making. I also like the idea with the white circle, we could make it so that hovering over a text 'How to read this' would show the circle with the picture on top of the visualisation.

**Comment by ianz88** [comment]
We don't really need the info about the proportion because the default view is by make it in equal size regardless of the population.

**Comment by Huiling0220** [comment]
> We don't really need the info about the proportion because the default view is by make it in equal size regardless of the population.

Yes, I have removed that part and made a new one for the standard version

**Comment by Huiling0220** [comment]
We have decided how to show the explanation picture, so I close this issues now
